#pragma once

/* XIAO ESP32-C5 in C5TAKO: 8 MB flash, 8 MB PSRAM, ST7789 240x240. */
#define BOARD_NAME "C5TAKO"
#define BOARD_ID "c5tako"
#define BOARD_TARGET "esp32c5"

#define BOARD_PIN_BUTTON_BOOT 4
#define BOARD_PIN_BATTERY_ADC 6
#define BOARD_PIN_BATTERY_EN 26
#define BOARD_BATTERY_DIVIDER_RATIO 2.0f
#define BOARD_PIN_BTN_LEFT 23
#define BOARD_PIN_BTN_OK 4
#define BOARD_PIN_BTN_UP 24
#define BOARD_PIN_BTN_RIGHT 0
#define BOARD_PIN_BTN_DOWN 28

#define BOARD_PIN_LCD_SCLK 8
#define BOARD_PIN_LCD_MOSI 10
#define BOARD_PIN_LCD_DC 1
#define BOARD_PIN_LCD_CS 7
#define BOARD_PIN_LCD_RST UINT16_MAX
#define BOARD_PIN_LCD_BL 25
#define BOARD_LCD_H_RES 240
#define BOARD_LCD_V_RES 240
#define BOARD_LCD_SPI_HOST SPI2_HOST
#define BOARD_LCD_SPI_FREQ_HZ (40 * 1000 * 1000)
#define BOARD_LCD_CMD_BITS 8
#define BOARD_LCD_PARAM_BITS 8
#define BOARD_LCD_SWAP_XY false
#define BOARD_LCD_MIRROR_X false
#define BOARD_LCD_MIRROR_Y false
#define BOARD_LCD_INVERT_COLOR true
#define BOARD_LCD_GAP_X 0
#define BOARD_LCD_GAP_Y 0
#define BOARD_LCD_BL_ACTIVE_LOW false
#define BOARD_LCD_COLOR_ORDER_BGR false
#define BOARD_LCD_FG_COLOR 0x20FD
#define BOARD_LCD_BG_COLOR 0x0000

#define BOARD_PIN_SD_CS 5
#define BOARD_PIN_SD_MISO 9
#define BOARD_SD_MAX_FREQ_KHZ 4000
#define BOARD_SD_POWER_SETTLE_MS 80
#define BOARD_SD_IDLE_CLOCK_BYTES 16
#define BOARD_PIN_CC1101_SCK 8
#define BOARD_PIN_CC1101_MOSI 10
#define BOARD_PIN_CC1101_MISO 9
#define BOARD_PIN_CC1101_CSN 2
#define BOARD_PIN_CC1101_GDO0 12
#define BOARD_PIN_CC1101_GDO2 11
#define BOARD_CC1101_SPI_SHARED 1
#define BOARD_PIN_BUZZER 3
#define BOARD_PIN_USER_LED 27

#define BOARD_PIN_TOUCH_SCL UINT16_MAX
#define BOARD_PIN_TOUCH_SDA UINT16_MAX
#define BOARD_PIN_TOUCH_RST UINT16_MAX
#define BOARD_PIN_TOUCH_INT UINT16_MAX
#define BOARD_TOUCH_I2C_ADDR 0
#define BOARD_TOUCH_I2C_PORT I2C_NUM_0
#define BOARD_TOUCH_I2C_FREQ_HZ 0
#define BOARD_TOUCH_I2C_TIMEOUT 0

#define BOARD_HAS_TOUCH 0
#define BOARD_HAS_ENCODER 0
#define BOARD_HAS_SD_CARD 1
#define BOARD_HAS_BLE 1
#define BOARD_HAS_RGB_LED 0
#define BOARD_HAS_VIBRO 0
#define BOARD_HAS_SPEAKER 0
#define BOARD_HAS_IR 0
#define BOARD_HAS_IBUTTON 0
#define BOARD_HAS_RFID 0
#define BOARD_HAS_NFC 0
#define BOARD_HAS_SUBGHZ 0
#define BOARD_HAS_NRF24 0
#define BOARD_HAS_MIC 0

#define BQ27220_ADDR 0x55
#define BQ25896_CHARGE_LIMIT 1280
#define FURI_HAL_POWER_VIRTUAL_CAPACITY_MAH (1300U)
